### PR TITLE
fix rubocop complains, activate rubocop again, add .rubocop_todo.yml

### LINKED ISSUE #9: Update ruby code to meet rubocops criterias
The rubocop linting is disabled atm. We should fix this. The ruby code has to be change so that rubocop is ok with it.

### PR DESCRIPTION
**Pull request by SimonHoenscheid**
#### This Pull Request (PR) fixes the following issues

Fixes #9 

There are 16 failed unit tests now. These are expecting stubbing now. Need to figure that out. Any hints welcome

### CODE REVIEW

**Comment by ananace** [comment]
`receive` and `have_received` are entirely different things; `expect(Class).to receive(:method)` would add a stub method onto a class, while `expect(Class).to have_received(:method)` only adds a spy on if an existing method has been called.

This is also seen in the messages on the `allow(Class).to ...` tests, since using `have_received` there is a no-op. (You're basically just saying "I don't mind if a method is called", which doesn't make much sense in a testing context.

**Comment by SimonHoenscheid** [comment]
@ananace interesting. The Rubocop messages left me with the impression these were interchangeable. I will have a closer look.

**Comment by SimonHoenscheid** [comment]
I decided to exclude these checks. Pipeline is now OK.

**Review by bastelfreak — APPROVED** [review]
looks okay to me, but we don't have acceptance tests to verify it's still working. It would be nice if someone else can take a look at well.

**Review by ananace — APPROVED** [review]
I personally dislike the period at the end of line change, but not going to hold things back on styling disagreements, especially against rubocop - which I assume is what prompted the change.

**Pull request merged**
