### PR TITLE
Release 1.0.0

### PR DESCRIPTION
**Pull request by rwaffen**

### CODE REVIEW

**Review by tuxmea — APPROVED** [review]

**Comment by ananace** [comment]
I'd like to get #42 in as well, since otherwise the generated kubeconfig receives complaints from official Kubernetes tooling - Helm as one example will complain loudly about the unsafe permissions.

**Comment by rwaffen** [comment]
okay, then i wait until this is done...

**Comment by rwaffen** [comment]
@ananace @bastelfreak : do we want to wait here for #61 or can I proceed when #65 is merged?

**Comment by tuxmea** [comment]
Any update available on Roberts question?

**Comment by bastelfreak** [comment]
I think we can merge this now. Nothing stops us in the future to make a new release, so we shouldn't wait.

**Pull request merged**
